import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DropdownElement } from "./components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;


}>) {
  const dropDown1 = [
    {buttonLabel:"Home", link:"/"},
    {buttonLabel:"Stats", link:"/stats"},
    {buttonLabel:"Google", link:"https://google.com"}
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-4">
          <img className='h-5 w-5 object-scale-down'src="./favicon.ico"/>
          <DropdownElement dropdownLabel="Dropdown" buttons={dropDown1} />
        </nav>
        {children}
      </body>
    </html>
  );
}
